language: cpp
dist: trusty
install:
  - sudo apt-get install libmozjs-24-dev libreadline-dev autoconf-archive
before_script:
  - autoreconf --version
  - g++ --version
script:
  - autoreconf -i && ./configure && make && make check

